//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Signature.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_Signature.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string const_cancel {
            get {
                return ResourceManager.GetString("const_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string const_save {
            get {
                return ResourceManager.GetString("const_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language: english.
        /// </summary>
        internal static string settingsview_la_selectedlanguage {
            get {
                return ResourceManager.GetString("settingsview_la_selectedlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsview_title {
            get {
                return ResourceManager.GetString("settingsview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string signaturepopup_btn_clear {
            get {
                return ResourceManager.GetString("signaturepopup_btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please collect the signature.
        /// </summary>
        internal static string signaturepopup_missingname {
            get {
                return ResourceManager.GetString("signaturepopup_missingname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign here.
        /// </summary>
        internal static string signaturepopup_sign {
            get {
                return ResourceManager.GetString("signaturepopup_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Enter a name.
        /// </summary>
        internal static string signaturepopup_watermarkname {
            get {
                return ResourceManager.GetString("signaturepopup_watermarkname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Signature.
        /// </summary>
        internal static string tripeventview_collectsignature {
            get {
                return ResourceManager.GetString("tripeventview_collectsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Trip: {0}.
        /// </summary>
        internal static string tripeventview_title {
            get {
                return ResourceManager.GetString("tripeventview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tripview_btn_opensettings {
            get {
                return ResourceManager.GetString("tripview_btn_opensettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string tripview_btn_refreshtrips {
            get {
                return ResourceManager.GetString("tripview_btn_refreshtrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Order / Trip.
        /// </summary>
        internal static string tripview_filter {
            get {
                return ResourceManager.GetString("tripview_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string tripview_title {
            get {
                return ResourceManager.GetString("tripview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripnumber.
        /// </summary>
        internal static string tripview_watermarkfilter {
            get {
                return ResourceManager.GetString("tripview_watermarkfilter", resourceCulture);
            }
        }
    }
}
